services:
  app:
    build: .
    restart: unless-stopped
    environment:
      - MD5_PASS
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/dist
      - /app/node_modules
      - /app/petlibro-client
